// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function subscribe(self, next, error, complete, param) {
  var args = {
    next: next,
    error: error,
    complete: complete
  };
  return self.subscribe(args);
}

export {
  subscribe ,
  
}
/* No side effect */
