// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Esm2015 from "rxjs/_esm2015";
import * as RxJs_Observable$ReasonRxjsPractice from "./rxjs/RxJs_Observable.bs.js";

console.log("Hello, BuckleScript and Reason!");

var observable = Esm2015.Observable.create((function (observer) {
        observer.next(1);
        observer.next(2);
        observer.next(3);
        setTimeout((function (param) {
                observer.next(4);
                observer.complete();
                return /* () */0;
              }), 1000);
        return ;
      }));

RxJs_Observable$ReasonRxjsPractice.subscribe(observable, (function (x) {
        console.log("got value", x);
        return /* () */0;
      }), (function (err) {
        console.log("something wrong occurred", err);
        return /* () */0;
      }), (function (param) {
        console.log("done");
        return /* () */0;
      }), /* () */0);

export {
  observable ,
  
}
/*  Not a pure module */
